# Generated by Django 3.1.7 on 2021-02-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_organizationmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmember',
            name='birthdate',
            field=models.DateField(verbose_name='Birthdate'),
        ),
    ]
