# Generated by Django 3.1.7 on 2021-03-01 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20210228_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmember',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Phone'),
        ),
    ]
