# Generated by Django 3.1.7 on 2021-03-01 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20210228_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Phone'),
        ),
    ]
