version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: organization_db

    volumes:
      - postgres_data:/var/lib/postgres/data/
    ports:
      - 5432:5432
  
  api:
    build: .    
    command: bash -c "
                       python /code/manage.py makemigrations --noinput
                       && python /code/manage.py migrate --noinput
                       && python /code/manage.py initial_data
                       && python /code/manage.py collectstatic --noinput
                       && python /code/manage.py runserver 0.0.0.0:8000
                        "

    ports:
      - "8001:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - DJANGO_SECRET_KEY=#aDAIv[}A~w;mo^qfqnM#FKP@]|7sl_3-^,T.u,Z?s3N~ti)@p
      - DATABASE_URL=postgres://root:root@postgres/organization_db
    depends_on:
      - postgres
  
volumes:
  postgres_data: